name: kaboom-game
services:
  - name: kaboom-game
    type: web
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_HOST
        value: postgres
      - name: POSTGRES_DB
        value: kaboom_game
      - name: POSTGRES_PASSWORD
        secret: postgres-password
      - name: POSTGRES_PORT
        value: "5432"
      - name: REDIS_URL
        value: redis://redis:6379
      - name: PORT
        value: "8080"
      - name: NODE_ENV
        value: production
    ports:
      - port: 8080
        protocol: http
    routes:
      - path: /
        protocol: http
    build:
      builder: nodejs
      buildCommand: npm install
    run:
      command: npm start
    envs:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_HOST
        value: postgres
      - name: POSTGRES_DB
        value: kaboom_game
      - name: POSTGRES_PASSWORD
        secret: postgres-password
      - name: POSTGRES_PORT
        value: "5432"
      - name: REDIS_URL
        value: redis://redis:6379
      - name: PORT
        value: "8080"
      - name: NODE_ENV
        value: production

  - name: postgres
    type: postgresql
    env:
      - name: POSTGRES_DB
        value: kaboom_game
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        secret: postgres-password

  - name: redis
    type: redis
    env:
      - name: REDIS_PASSWORD
        secret: redis-password
