[build]
  command = "npm install"
  publish = "."

[build.environment]
  NODE_ENV = "production"
  PORT = "3000"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
