name: Test Kaboom Game

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Test server startup
      run: |
        npm start &
        sleep 5
        curl -f http://localhost:3000/api/health || exit 1
    
    - name: Check for vulnerabilities
      run: npm audit --audit-level moderate
    
    - name: Test API endpoints
      run: |
        curl -f http://localhost:3000/api/health
        curl -f http://localhost:3000/api/players
        echo "✅ All API endpoints working"


